# Generated by Django 4.2.30 on 2026-07-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullaniciprofili',
            name='dogum_saati',
            field=models.TimeField(blank=True, null=True, verbose_name='Doğum Saati'),
        ),
        migrations.AlterField(
            model_name='kullaniciprofili',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='kullaniciprofili',
            name='dogum_yeri',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Doğum Yeri'),
        ),
    ]
