# Generated by Django 4.2.30 on 2026-07-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BurcYorumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burc', models.CharField(choices=[('koc', 'Koç'), ('boga', 'Boğa'), ('ikizler', 'İkizler'), ('yengec', 'Yengeç'), ('aslan', 'Aslan'), ('basak', 'Başak'), ('terazi', 'Terazi'), ('akrep', 'Akrep'), ('yay', 'Yay'), ('oglak', 'Oğlak'), ('kova', 'Kova'), ('balik', 'Balık')], max_length=20)),
                ('tarih', models.DateField()),
                ('yorum', models.TextField()),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
