# Generated by Django 4.2.30 on 2026-07-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burcs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burcyorumu',
            name='tarih',
        ),
        migrations.AddField(
            model_name='burcyorumu',
            name='ay',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='burcyorumu',
            name='periyot',
            field=models.CharField(choices=[('aylik', 'Aylık')], default='aylik', max_length=10),
        ),
        migrations.AddField(
            model_name='burcyorumu',
            name='yil',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
