# Generated by Django 4.2.30 on 2026-07-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burcs', '0002_remove_burcyorumu_tarih_burcyorumu_ay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GunlukYorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burc', models.CharField(max_length=20)),
                ('tarih', models.DateField()),
                ('yorum', models.TextField()),
                ('olusturulma_zamani', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('burc', 'tarih')},
            },
        ),
    ]
