# Generated by Django 4.2.30 on 2026-08-05 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burcs', '0003_gunlukyorum'),
    ]

    operations = [
        migrations.CreateModel(
            name='KozmikTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="URL'de görünecek isim (Örn: hangi-hayvansin)", unique=True)),
                ('aciklama', models.TextField()),
                ('ikon', models.CharField(help_text='FontAwesome class (Örn: fa-paw)', max_length=50)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_kodu', models.CharField(help_text='Örn: aslan, lofi, earth_water', max_length=50)),
                ('baslik', models.CharField(max_length=100)),
                ('ikon', models.CharField(help_text='Emoji veya ikon (Örn: 🦁)', max_length=50)),
                ('aciklama', models.TextField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonuclar', to='burcs.kozmiktest')),
            ],
        ),
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.PositiveIntegerField(default=1)),
                ('metin', models.CharField(max_length=300)),
                ('gorsel_url', models.URLField(blank=True, help_text='Soru için GIF/Resim linki (Giphy, Imgur vb.)', null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorular', to='burcs.kozmiktest')),
            ],
            options={
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='Secenek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.CharField(max_length=200)),
                ('kategori_kodu', models.CharField(help_text='Bu seçenek hangi sonuca puan verecek?', max_length=50)),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secenekler', to='burcs.soru')),
            ],
        ),
    ]
