# Generated by Django 4.2.30 on 2026-07-13 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DogumHaritasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogum_tarihi', models.DateField()),
                ('dogum_saati', models.TimeField()),
                ('dogum_yeri', models.CharField(blank=True, max_length=100)),
                ('gezegen_konumlari', models.JSONField()),
                ('ai_yorumu', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogum_haritalari', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
