# Generated by Django 4.2.30 on 2026-07-16 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogum_haritasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogumharitasi',
            name='isim',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dogumharitasi',
            name='kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dogum_haritalari', to=settings.AUTH_USER_MODEL),
        ),
    ]
