# Generated by Django 4.2.30 on 2026-07-21 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumerolojiSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('dogum_tarihi', models.DateField()),
                ('yasam_yolu_sayisi', models.IntegerField()),
                ('kader_sayisi', models.IntegerField()),
                ('ai_yorumu', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeroloji_sonuclari', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
