# Generated by Django 4.2.30 on 2026-08-01 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('numeroloji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerolojisonucu',
            name='kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='numeroloji_sonucu', to=settings.AUTH_USER_MODEL),
        ),
    ]
