# Generated by Django 4.2.30 on 2026-07-22 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvYorumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_no', models.IntegerField()),
                ('burc', models.CharField(max_length=20)),
                ('dogum_tarihi', models.DateField()),
                ('dogum_saati', models.TimeField()),
                ('ai_yorumu', models.TextField()),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_yorumlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('kullanici', 'ev_no', 'dogum_tarihi', 'dogum_saati')},
            },
        ),
    ]
