# Generated by Django 4.2.30 on 2026-07-16 07:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uyumluluk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyumluluktesti',
            name='kisi1_dogum_saati',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='uyumluluktesti',
            name='kisi1_dogum_tarihi',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='uyumluluktesti',
            name='kisi1_dogum_yeri',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='uyumluluktesti',
            name='kisi1_isim',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='uyumluluktesti',
            name='ai_yorumu',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='uyumluluktesti',
            name='kisi1_gezegenler',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='uyumluluktesti',
            name='kisi2_dogum_saati',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='uyumluluktesti',
            name='kisi2_dogum_tarihi',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='uyumluluktesti',
            name='kisi2_dogum_yeri',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='uyumluluktesti',
            name='kisi2_gezegenler',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='uyumluluktesti',
            name='kisi2_isim',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='uyumluluktesti',
            name='kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uyumluluk_testleri', to=settings.AUTH_USER_MODEL),
        ),
    ]
