# Generated by Django 4.2.30 on 2026-07-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstroGundem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(help_text='Örn: Merkür Retrosu', max_length=150)),
                ('tur', models.CharField(choices=[('retro', 'Retro'), ('dolunay', 'Dolunay'), ('yeniay', 'Yeni Ay'), ('burc_gecisi', 'Burç Geçişi'), ('tutulma', 'Tutulma'), ('diger', 'Diğer')], default='diger', max_length=20)),
                ('baslangic_tarihi', models.DateField()),
                ('bitis_tarihi', models.DateField()),
                ('kisa_aciklama', models.CharField(help_text='Kart üzerinde görünecek kısa özet', max_length=200)),
                ('detay_aciklama', models.TextField(help_text='Bu olayın ne anlama geldiğine dair detaylı açıklama')),
                ('etkilenen_burclar', models.CharField(blank=True, help_text='Opsiyonel, virgülle ayır: Koç, Boğa, İkizler', max_length=200)),
                ('aktif_mi', models.BooleanField(default=True, help_text='Anasayfada gösterilsin mi?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-baslangic_tarihi'],
            },
        ),
    ]
