# Generated by Django 4.2.30 on 2026-07-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unlu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('meslek', models.CharField(blank=True, max_length=100)),
                ('dogum_tarihi', models.DateField()),
                ('dogum_saati', models.TimeField(default='12:00')),
                ('dogum_yeri', models.CharField(blank=True, max_length=100)),
                ('gorsel_url', models.URLField(blank=True, help_text='Ünlünün fotoğraf linki (opsiyonel)')),
            ],
        ),
    ]
